### ISSUE TITLE
Executors are started before the scheduler

### ISSUE THREAD

**Issue by iajoiner** [spaceandtimelabs/arrow-ballista#10]
**Describe the bug**
The executors should depend on the scheduler.

**To Reproduce** 
`docker-compose up --build`

**Expected behavior**
The scheduler should start before the executors.

**Comment by avantgardnerio** [comment]
Attaching to arrow-ballista_ballista-client_1, arrow-ballista_ballista-executor_2, arrow-ballista_ballista-executor_1, arrow-ballista_ballista-scheduler_1, arrow-ballista_etcd_1
[33mballista-executor_1   |[0m [2m2022-09-23T15:27:32.026075Z[0m [32m INFO[0m main ThreadId(01) [2mballista_executor[0m[2m:[0m Running with config:    
[33mballista-executor_1   |[0m [2m2022-09-23T15:27:32.026091Z[0m [32m INFO[0m main ThreadId(01) [2mballista_executor[0m[2m:[0m work_dir: /tmp/.tmph9SQf5    
[33mballista-executor_1   |[0m [2m2022-09-23T15:27:32.026094Z[0m [32m INFO[0m main ThreadId(01) [2mballista_executor[0m[2m:[0m concurrent_tasks: 20    
[33mballista-executor_1   |[0m [2m2022-09-23T15:27:32.026860Z[0m [32m INFO[0m tokio-runtime-worker ThreadId(16) [2mballista_executor::execution_loop[0m[2m:[0m Starting poll work loop with scheduler    
[33mballista-executor_1   |[0m [2m2022-09-23T15:27:32.026877Z[0m [32m INFO[0m tokio-runtime-worker ThreadId(02) [2mballista_executor[0m[2m:[0m Ballista v0.8.0 Rust Executor Flight Server listening on 0.0.0.0:50051    
[33mballista-executor_1   |[0m [2m2022-09-23T15:45:41.160989Z[0m [32m INFO[0m main ThreadId(01) [2mballista_executor[0m[2m:[0m Running with config:    
[33mballista-executor_1   |[0m [2m2022-09-23T15:45:41.161005Z[0m [32m INFO[0m main ThreadId(01) [2mballista_executor[0m[2m:[0m work_dir: /tmp/.tmpkTeb4i    
[33mballista-executor_1   |[0m [2m2022-09-23T15:45:41.161007Z[0m [32m INFO[0m main ThreadId(01) [2mballista_executor[0m[2m:[0m concurrent_tasks: 20    
[33mballista-executor_1   |[0m Error: Could not connect to scheduler
[33mballista-executor_1   |[0m 
[33mballista-executor_1   |[0m Caused by:
[33mballista-executor_1   |[0m     0: transport error
[33mballista-executor_1   |[0m     1: error trying to connect: tcp connect error: Connection refused (os error 111)
[33mballista-executor_1   |[0m     2: tcp connect error: Connection refused (os error 111)
[33mballista-executor_1   |[0m     3: Connection refused (os error 111)
[36mballista-client_1     |[0m /bin/sh: 0: cannot open sleep: No such file
[36mballista-client_1     |[0m /bin/sh: 0: cannot open sleep: No such file
[32mballista-executor_2   |[0m [2m2022-09-23T15:27:31.931180Z[0m [32m INFO[0m main ThreadId(01) [2mballista_executor[0m[2m:[0m Running with config:    
[32mballista-executor_2   |[0m [2m2022-09-23T15:27:31.931196Z[0m [32m INFO[0m main ThreadId(01) [2mballista_executor[0m[2m:[0m work_dir: /tmp/.tmpr5gT98    
[32mballista-executor_2   |[0m [2m2022-09-23T15:27:31.931198Z[0m [32m INFO[0m main ThreadId(01) [2mballista_executor[0m[2m:[0m concurrent_tasks: 20    
[32mballista-executor_2   |[0m [2m2022-09-23T15:27:31.932180Z[0m [32m INFO[0m tokio-runtime-worker ThreadId(18) [2mballista_executor[0m[2m:[0m Ballista v0.8.0 Rust Executor Flight Server listening on 0.0.0.0:50051    
[32mballista-executor_2   |[0m [2m2022-09-23T15:27:31.932186Z[0m [32m INFO[0m tokio-runtime-worker ThreadId(20) [2mballista_executor::execution_loop[0m[2m:[0m Starting poll work loop with scheduler    
[32mballista-executor_2   |[0m [2m2022-09-23T15:45:40.977541Z[0m [32m INFO[0m main ThreadId(01) [2mballista_executor[0m[2m:[0m Running with config:    
[32mballista-executor_2   |[0m [2m2022-09-23T15:45:40.977557Z[0m [32m INFO[0m main ThreadId(01) [2mballista_executor[0m[2m:[0m work_dir: /tmp/.tmpbrTAu0    
[32mballista-executor_2   |[0m [2m2022-09-23T15:45:40.977559Z[0m [32m INFO[0m main ThreadId(01) [2mballista_executor[0m[2m:[0m concurrent_tasks: 20    
[32mballista-executor_2   |[0m Error: Could not connect to scheduler
[32mballista-executor_2   |[0m 
[32mballista-executor_2   |[0m Caused by:
[32mballista-executor_2   |[0m     0: transport error
[32mballista-executor_2   |[0m     1: error trying to connect: tcp connect error: Connection refused (os error 111)
[32mballista-executor_2   |[0m     2: tcp connect error: Connection refused (os error 111)
[32mballista-executor_2   |[0m     3: Connection refused (os error 111)
[35mballista-scheduler_1  |[0m Starting nginx to serve Ballista Scheduler web UI on port 80
[35mballista-scheduler_1  |[0m nohup: failed to run command 'nginx': No such file or directory
[35mballista-scheduler_1  |[0m [2m2022-09-23T15:27:31.268916Z[0m [32m INFO[0m main ThreadId(01) [2mballista_scheduler[0m[2m:[0m Ballista v0.8.0 Scheduler listening on 0.0.0.0:50050    
[35mballista-scheduler_1  |[0m [2m2022-09-23T15:27:31.268932Z[0m [32m INFO[0m main ThreadId(01) [2mballista_scheduler[0m[2m:[0m Starting Scheduler grpc server with task scheduling policy of PullStaged    
[35mballista-scheduler_1  |[0m [2m2022-09-23T15:27:31.271473Z[0m [32m INFO[0m main ThreadId(01) [2mballista_scheduler::scheduler_server::query_stage_scheduler[0m[2m:[0m Starting QueryStageScheduler    
[35mballista-scheduler_1  |[0m [2m2022-09-23T15:27:31.271498Z[0m [32m INFO[0m tokio-runtime-worker ThreadId(21) [2mballista_core::event_loop[0m[2m:[0m Starting the event loop query_stage    
[35mballista-scheduler_1  |[0m Starting nginx to serve Ballista Scheduler web UI on port 80
[35mballista-scheduler_1  |[0m nohup: failed to run command 'nginx': No such file or directory
[35mballista-scheduler_1  |[0m [2m2022-09-23T15:45:40.264678Z[0m [32m INFO[0m main ThreadId(01) [2mballista_scheduler[0m[2m:[0m Ballista v0.8.0 Scheduler listening on 0.0.0.0:50050    
[35mballista-scheduler_1  |[0m [2m2022-09-23T15:45:40.264697Z[0m [32m INFO[0m main ThreadId(01) [2mballista_scheduler[0m[2m:[0m Starting Scheduler grpc server with task scheduling policy of PullStaged    
[35mballista-scheduler_1  |[0m [2m2022-09-23T15:45:41.634456Z[0m [32m INFO[0m main ThreadId(01) [2mballista_scheduler::scheduler_server::query_stage_scheduler[0m[2m:[0m Starting QueryStageScheduler    
[35mballista-scheduler_1  |[0m [2m2022-09-23T15:45:41.634518Z[0m [32m INFO[0m tokio-runtime-worker ThreadId(03) [2mballista_core::event_loop[0m[2m:[0m Starting the event loop query_stage    
[35mballista-scheduler_1  |[0m [2m2022-09-23T15:48:41.635509Z[0m [33m WARN[0m tokio-runtime-worker ThreadId(03) [2mballista_scheduler::scheduler_server[0m[2m:[0m Executor cb5433ab-8a6b-47ad-96a0-2541284ebf9a heartbeat timed out after 180s    
[35mballista-scheduler_1  |[0m [2m2022-09-23T15:48:44.716728Z[0m [33m WARN[0m tokio-runtime-worker ThreadId(14) [2mballista_scheduler::scheduler_server[0m[2m:[0m Executor is already dead, failed to connect to Executor cb5433ab-8a6b-47ad-96a0-2541284ebf9a    
[35mballista-scheduler_1  |[0m [2m2022-09-23T15:48:44.716802Z[0m [33m WARN[0m tokio-runtime-worker ThreadId(14) [2mballista_scheduler::scheduler_server[0m[2m:[0m Executor bfeb5534-1954-4a96-b9fe-653ba62ee8f1 heartbeat timed out after 180s    
[35mballista-scheduler_1  |[0m [2m2022-09-23T15:48:47.792569Z[0m [33m WARN[0m tokio-runtime-worker ThreadId(19) [2mballista_scheduler::scheduler_server[0m[2m:[0m Executor is already dead, failed to connect to Executor bfeb5534-1954-4a96-b9fe-653ba62ee8f1    
[34metcd_1                |[0m [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
[34metcd_1                |[0m 2022-09-23 15:27:30.691094 I | etcdmain: etcd Version: 3.4.9
[34metcd_1                |[0m 2022-09-23 15:27:30.691120 I | etcdmain: Git SHA: 54ba95891
[34metcd_1                |[0m 2022-09-23 15:27:30.691122 I | etcdmain: Go Version: go1.12.17
[34metcd_1                |[0m 2022-09-23 15:27:30.691124 I | etcdmain: Go OS/Arch: linux/amd64
[34metcd_1                |[0m 2022-09-23 15:27:30.691127 I | etcdmain: setting maximum number of CPUs to 20, total number of available CPUs is 20
[34metcd_1                |[0m 2022-09-23 15:27:30.691132 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
[34metcd_1                |[0m [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
[34metcd_1                |[0m 2022-09-23 15:27:30.691408 I | embed: name = default
[34metcd_1                |[0m 2022-09-23 15:27:30.691412 I | embed: data dir = default.etcd
[34metcd_1                |[0m 2022-09-23 15:27:30.691414 I | embed: member dir = default.etcd/member
[34metcd_1                |[0m 2022-09-23 15:27:30.691416 I | embed: heartbeat = 100ms
[34metcd_1                |[0m 2022-09-23 15:27:30.691418 I | embed: election = 1000ms
[34metcd_1                |[0m 2022-09-23 15:27:30.691419 I | embed: snapshot count = 100000
[34metcd_1                |[0m 2022-09-23 15:27:30.691426 I | embed: advertise client URLs = http://etcd:2379
[34metcd_1                |[0m 2022-09-23 15:27:30.733900 I | etcdserver: starting member 8e9e05c52164694d in cluster cdf818194e3a8c32
[34metcd_1                |[0m raft2022/09/23 15:27:30 INFO: 8e9e05c52164694d switched to configuration voters=()
[34metcd_1                |[0m raft2022/09/23 15:27:30 INFO: 8e9e05c52164694d became follower at term 0
[34metcd_1                |[0m raft2022/09/23 15:27:30 INFO: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
[34metcd_1                |[0m raft2022/09/23 15:27:30 INFO: 8e9e05c52164694d became follower at term 1
[34metcd_1                |[0m raft2022/09/23 15:27:30 INFO: 8e9e05c52164694d switched to configuration voters=(10276657743932975437)
[34metcd_1                |[0m 2022-09-23 15:27:30.754380 W | auth: simple token is not cryptographically signed
[34metcd_1                |[0m 2022-09-23 15:27:30.786359 I | etcdserver: starting server... [version: 3.4.9, cluster version: to_be_decided]
[34metcd_1                |[0m 2022-09-23 15:27:30.786646 I | etcdserver: 8e9e05c52164694d as single-node; fast-forwarding 9 ticks (election ticks 10)
[34metcd_1                |[0m raft2022/09/23 15:27:30 INFO: 8e9e05c52164694d switched to configuration voters=(10276657743932975437)
[34metcd_1                |[0m 2022-09-23 15:27:30.787004 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
[34metcd_1                |[0m 2022-09-23 15:27:30.787667 I | embed: listening for peers on 127.0.0.1:2380
[34metcd_1                |[0m raft2022/09/23 15:27:30 INFO: 8e9e05c52164694d is starting a new election at term 1
[34metcd_1                |[0m raft2022/09/23 15:27:30 INFO: 8e9e05c52164694d became candidate at term 2
[34metcd_1                |[0m raft2022/09/23 15:27:30 INFO: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 2
[34metcd_1                |[0m raft2022/09/23 15:27:30 INFO: 8e9e05c52164694d became leader at term 2
[34metcd_1                |[0m raft2022/09/23 15:27:30 INFO: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 2
[34metcd_1                |[0m 2022-09-23 15:27:30.935285 I | embed: ready to serve client requests
[34metcd_1                |[0m 2022-09-23 15:27:30.935318 I | etcdserver: setting up the initial cluster version to 3.4
[34metcd_1                |[0m 2022-09-23 15:27:30.935489 I | etcdserver: published {Name:default ClientURLs:[http://etcd:2379]} to cluster cdf818194e3a8c32
[34metcd_1                |[0m 2022-09-23 15:27:30.937176 N | embed: serving insecure client requests on [::]:2379, this is strongly discouraged!
[34metcd_1                |[0m 2022-09-23 15:27:30.940395 N | etcdserver/membership: set the initial cluster version to 3.4
[34metcd_1                |[0m 2022-09-23 15:27:30.940529 I | etcdserver/api: enabled capabilities for version 3.4
[34metcd_1                |[0m 2022-09-23 15:45:25.498890 N | pkg/osutil: received terminated signal, shutting down...
[34metcd_1                |[0m 2022-09-23 15:45:25.499052 I | etcdserver: skipped leadership transfer for single voting member cluster
[34metcd_1                |[0m [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
[34metcd_1                |[0m 2022-09-23 15:45:39.720156 I | etcdmain: etcd Version: 3.4.9
[34metcd_1                |[0m 2022-09-23 15:45:39.720179 I | etcdmain: Git SHA: 54ba95891
[34metcd_1                |[0m 2022-09-23 15:45:39.720182 I | etcdmain: Go Version: go1.12.17
[34metcd_1                |[0m 2022-09-23 15:45:39.720184 I | etcdmain: Go OS/Arch: linux/amd64
[34metcd_1                |[0m 2022-09-23 15:45:39.720186 I | etcdmain: setting maximum number of CPUs to 20, total number of available CPUs is 20
[34metcd_1                |[0m 2022-09-23 15:45:39.720190 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
[34metcd_1                |[0m 2022-09-23 15:45:39.720246 N | etcdmain: the server is already initialized as member before, starting as etcd member...
[34metcd_1                |[0m [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
[34metcd_1                |[0m 2022-09-23 15:45:39.720556 I | embed: name = default
[34metcd_1                |[0m 2022-09-23 15:45:39.720561 I | embed: data dir = default.etcd
[34metcd_1                |[0m 2022-09-23 15:45:39.720563 I | embed: member dir = default.etcd/member
[34metcd_1                |[0m 2022-09-23 15:45:39.720565 I | embed: heartbeat = 100ms
[34metcd_1                |[0m 2022-09-23 15:45:39.720567 I | embed: election = 1000ms
[34metcd_1                |[0m 2022-09-23 15:45:39.720568 I | embed: snapshot count = 100000
[34metcd_1                |[0m 2022-09-23 15:45:39.720573 I | embed: advertise client URLs = http://etcd:2379
[34metcd_1                |[0m 2022-09-23 15:45:39.720576 I | embed: initial advertise peer URLs = http://localhost:2380
[34metcd_1                |[0m 2022-09-23 15:45:39.720579 I | embed: initial cluster = 
[34metcd_1                |[0m 2022-09-23 15:45:39.805129 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 40128
[34metcd_1                |[0m raft2022/09/23 15:45:39 INFO: 8e9e05c52164694d switched to configuration voters=()
[34metcd_1                |[0m raft2022/09/23 15:45:39 INFO: 8e9e05c52164694d became follower at term 2
[34metcd_1                |[0m raft2022/09/23 15:45:39 INFO: newRaft 8e9e05c52164694d [peers: [], term: 2, commit: 40128, applied: 0, lastindex: 40128, lastterm: 2]
[34metcd_1                |[0m 2022-09-23 15:45:39.824700 W | auth: simple token is not cryptographically signed
[34metcd_1                |[0m 2022-09-23 15:45:39.930790 I | etcdserver: starting server... [version: 3.4.9, cluster version: to_be_decided]
[34metcd_1                |[0m raft2022/09/23 15:45:39 INFO: 8e9e05c52164694d switched to configuration voters=(10276657743932975437)
[34metcd_1                |[0m 2022-09-23 15:45:39.931915 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
[34metcd_1                |[0m 2022-09-23 15:45:39.932127 N | etcdserver/membership: set the initial cluster version to 3.4
[34metcd_1                |[0m 2022-09-23 15:45:39.932173 I | etcdserver/api: enabled capabilities for version 3.4
[34metcd_1                |[0m 2022-09-23 15:45:39.934818 I | embed: listening for peers on 127.0.0.1:2380
[34metcd_1                |[0m raft2022/09/23 15:45:41 INFO: 8e9e05c52164694d is starting a new election at term 2
[34metcd_1                |[0m raft2022/09/23 15:45:41 INFO: 8e9e05c52164694d became candidate at term 3
[34metcd_1                |[0m raft2022/09/23 15:45:41 INFO: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 3
[34metcd_1                |[0m raft2022/09/23 15:45:41 INFO: 8e9e05c52164694d became leader at term 3
[34metcd_1                |[0m raft2022/09/23 15:45:41 INFO: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 3
[34metcd_1                |[0m 2022-09-23 15:45:41.607759 I | etcdserver: published {Name:default ClientURLs:[http://etcd:2379]} to cluster cdf818194e3a8c32
[34metcd_1                |[0m 2022-09-23 15:45:41.607836 I | embed: ready to serve client requests
[34metcd_1                |[0m 2022-09-23 15:45:41.609278 N | embed: serving insecure client requests on [::]:2379, this is strongly discouraged!
[34metcd_1                |[0m 2022-09-23 17:18:01.798225 N | pkg/osutil: received terminated signal, shutting down...
[34metcd_1                |[0m 2022-09-23 17:18:01.798627 I | etcdserver: skipped leadership transfer for single voting member cluster

**Comment by avantgardnerio** [comment]
apt-get -y install coreutils nginx

**Comment by avantgardnerio** [comment]
https://medium.com/geekculture/how-to-successfully-implement-a-healthcheck-in-docker-compose-efced60bc08e
https://www.baeldung.com/ops/docker-compose-links-depends-on

**Comment by avantgardnerio** [comment]
I created an issue here: https://github.com/apache/arrow-ballista/issues/267

**Comment by iajoiner** [comment]
@avantgardnerio Closed as resolved here: https://github.com/apache/arrow-ballista/pull/268
